# Nombre de tu aplicación
spring.application.name=compra-ya-backend

# Puerto donde correrá el servidor (por defecto 8080)
server.port=8080

# Configuración de MongoDB (Esto es necesario para que no te dé error al arrancar)
# Si aún no tienes MongoDB instalado, puedes usar una base de datos en la nube (MongoDB Atlas)
spring.data.mongodb.uri=mongodb://localhost:27017/compraya
<script src="api.js"></script>
  # Reemplaza <password> por la contraseña que acabas de crear en el móvil
spring.data.mongodb.uri=mongodb+srv://owono:<Sanvalentin1#>@cluster0.xxxx.mongodb.net/compraya?retryWrites=true&w=majority